name: compile bzip by gcc and msvc on windows arm64
on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      
      - name: Create dist directory.
        run: mkdir -p dist

      - name: Build bzip2c with msvc for Windows
        shell: bash
        continue-on-error: true
        run: |
          cd bzip2/bzip2
          nmake -f makefile.msc
          cp bzip2.exe ../../dist/bzip2_amd64_windows_msvc.exe

      - name: Build bzip2c with gcc
        shell: bash
        continue-on-error: true
        run: |
          cd bzip2/bzip2
          gcc --version
          make clean
          make
          cp bzip2.exe ../../dist/bzip2_amd64_windows_gcc.exe

      - name: Build bzip2c with clang
        shell: bash
        continue-on-error: true
        run: |
          clang --version
          make clean
          make CC=clang
          cp bzip2.exe ../../dist/bzip2_amd64_windows_clang.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.target }}
          path: dist
