name: compile in windows
on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build:
    name: Build for Windows
    # runs-on: windows-latest
    runs-on: windows-11-arm
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Setup Rust
        run: |
          mkdir -p dist
          rustup update stable
          rustup target add ${{ matrix.target }}
          cargo install cargo-zigbuild

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # - name: Setup TinyGo
      #   uses: acifani/setup-tinygo@v2
      #   with:
      #     tinygo-version: '0.40.0'

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build bzip2c with msvc for Windows
        shell: bash
        run: |
          cd bzip2/bzip2
          nmake -f makefile.msc
          cp bzip2${{ matrix.extension }} ../../dist/bzip2_${{ matrix.arch }}_windows_msvc${{ matrix.extension }}

      # - name: Build Go
      #   shell: bash
      #   run: |
      #     cd bzip2/bzip2go
      #     go build -o ../../dist/bzip2_${{ matrix.arch }}_windows_go${{ matrix.extension }} cmd/bzip2/main.go

      - name: Build bzip2c with gcc
        shell: bash
        run: |
          cd bzip2/bzip2
          gcc --version
          make
          cp bzip2${{ matrix.extension }} ../../dist/bzip2_${{ matrix.arch }}_windows_gcc${{ matrix.extension }}

      - name: Build bzip2c with clang
        shell: bash
        run: |
          clang --version
          make clean
          make CC=clang
          cp bzip2${{ matrix.extension }} ../../dist/bzip2_${{ matrix.arch }}_windows_clang${{ matrix.extension }}

      # - name: Build with TinyGo for not Windows
      #   shell: bash
      #   run: |
      #     cd bzip2/bzip2go
      #     export CGO_ENABLED=1
      #     # tinygo build -o ../../dist/bzip2_${{ matrix.arch }}_windows_tgo${{ matrix.extension }} cmd/bzip2/main.go

      # - name: Build Rust
      #   shell: bash
      #   run: |
      #     cd bzip2/bzip2rs
      #     cargo zigbuild --release --features sys --target ${{ matrix.target }} --target-dir target/sys
      #     cargo zigbuild --release --target ${{ matrix.target }}                --target-dir target/pure
      #     # cargo build --release --features sys --target-dir target/sys
      #     # cargo build --release                --target-dir target/pure
      #     ls -R target
      #     cp target/sys/${{ matrix.target }}/release/bzip2rs  ../../dist/bzip2rs-sys-${{ matrix.target }}
      #     cp target/pure/${{ matrix.target }}/release/bzip2rs ../../dist/bzip2rs-pure-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.target }}
          path: dist
