name: compile bzip (arm64)
on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build-gcc:
    name: Build for Windows ARM64 with GCC
    runs-on: windows-11-arm
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive
          
      # 👇 MSYS2 の ARM64 ネイティブ環境（CLANGARM64）をセットアップ
      - name: Setup MSYS2 for Windows ARM64
        uses: msys2/setup-msys2@v2
        continue-on-error: true
        with:
          msystem: MSYS
          update: true
          # ARM64 ネイティブ向けのツールチェーンをインストール
          install: >-
            mingw-w64-cross-mingwarm64-gcc
            make

      - name: Build bzip2c with gcc
        shell: msys2 {0}
        continue-on-error: true
        run: |
          cd bzip2/bzip2
          aarch64-w64-mingw32-gcc --version
          make clean
          make CC=aarch64-w64-mingw32-gcc
          cp bzip2.exe ../../dist/bzip2_arm64_windows_gcc.exe

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-arm64-windows-gcc-msvc
          path: dist

  build-clang:
    name: Build for Windows ARM64 with clang
    runs-on: windows-11-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: Create dist directory.
        run: mkdir -p dist

      - name: Build bzip2c with msvc for Windows
        shell: bash
        continue-on-error: true
        run: |
          cd bzip2/bzip2
          nmake -f makefile.msc
          cp bzip2.exe ../../dist/bzip2_arm64_windows_msvc.exe

      - name: Build bzip2c with clang
        shell: bash
        continue-on-error: true
        run: |
          mkdir -p dist
          cd bzip2/bzip2
          clang --version
          make clean
          # same as clang for amd64.
          clang --target=arm64-pc-windows-msvc -O2 -g -D_FILE_OFFSET_BITS=64 -o bzip2.exe bzip2.c blocksort.c huffman.c crctable.c randtable.c compress.c decompress.c bzlib.c
          cp bzip2.exe ../../dist/bzip2_arm64_windows_clang.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-arm64-windows-clang
          path: dist
